FROM node:14.18.2

ARG NODE_ENV

ENV NODE_ENV = ${NODE_ENV}
ENV PATH /app/node_modules/.bin:$PATH

COPY package*.json ./

RUN npm install 

COPY . .
RUN npm run build
CMD  npm run full-stack 

EXPOSE 3000
EXPOSE 5000